development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  APP_ID: <%= ENV["APP_ID"] %>
  APP_SECRET: <%= ENV["APP_SECRET"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  APP_ID: <%= ENV["APP_ID"] %>
  APP_SECRET: <%= ENV["APP_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  APP_ID: <%= ENV["APP_ID"] %>
  APP_SECRET: <%= ENV["APP_SECRET"] %>