development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  APP_ID: <%= ENV["APP_ID"] %>
  APP_SECRET: <%= ENV["APP_SECRET"] %>
  FITBIT_CLIENT_KEY: <%= ENV["FITBIT_CLIENT_KEY"] %>
  FITBIT_CLIENT_SECRET: <%= ENV["FITBIT_CLIENT_SECRET"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  APP_ID: <%= ENV["APP_ID"] %>
  APP_SECRET: <%= ENV["APP_SECRET"] %>
  FITBIT_CLIENT_KEY: <%= ENV["FITBIT_CLIENT_KEY"] %>
  FITBIT_CLIENT_SECRET: <%= ENV["FITBIT_CLIENT_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  APP_ID: <%= ENV["APP_ID"] %>
  APP_SECRET: <%= ENV["APP_SECRET"] %>
  FITBIT_CLIENT_KEY: <%= ENV["FITBIT_CLIENT_KEY"] %>
  FITBIT_CLIENT_SECRET: <%= ENV["FITBIT_CLIENT_SECRET"] %>